name: lirc_client
description: Dart library for sending and receiving IR signals with lirc using unix sockets.
version: 0.2.0
homepage: https://github.com/julemand101/lirc_client/

environment:
  sdk: "^3.5.0"

dependencies:
  stream_transform: ^2.1.0

dev_dependencies:
  lints: ^4.0.0
